[package]
name = "ticc"
version = "0.1.0"
authors = ["djade <djadenkus@gmail.com>"]
edition = "2018"

[dependencies]
ticc-syntax = { path = "../ticc-syntax" }
logos = "0.11.4"
codespan-reporting = "0.11.0"
