[package]
name = "ticc-eval"
version = "0.1.0"
authors = ["djade <djadenkus@gmail.com>"]
edition = "2018"

[dependencies]
ticc-core = { path = "../ticc-core" }
memmap2 = "0.9.3"
iced-x86 = { version = "1.20.0", features = ["code_asm"] }
