[package]
name = "ticc-tests"
version = "0.1.0"
authors = ["djade <djadenkus@gmail.com>"]
edition = "2018"

[lib]
doctest = false

[[bin]]
name = "ticc-tests"
path = "src/main.rs"
doctest = false

[dependencies]
ticc = { path = "../ticc" }
codespan-reporting = "0.11.0"
